driverProperty=webdriver.chrome.driver
System.setProperty("webdriver.chrome.driver", "C:\\Users\\QUIKCARE COMPUTERS\\eclipse-workspace\\Repository\\chromedriver.exe");
Driverpath=.\\src\\com\\projectName\\drivers\\
        URL_1=https://testautomationpractice.blogspot.com/
        URL_2="www.paytm.com"
        browser=chrome;