driverProperty=webdriver.chrome.driver
driverPath=C:/Users/QUIKCARE COMPUTERS/eclipse-workspace/chromedriver.exe
browser=chrome
URL_1=https://testautomationpractice.blogspot.com/
URL_2=https://www.amazon.in/
Excellsheet=Sheet1
log4JPropertiesFileLoc=C:\Users\QUIKCARE COMPUTERS\eclipse-workspace\Automation_Pgm\Automation_Selenium_Pgm\Repository\log4j.properties