Name=//input[@id='name']
Email=//input[@id='email']
Country=//select[@id='country']/option
amazonSearchBox=//input[@id='twotabsearchtextbox']
headerText1 = //span[text()='For Selenium, Cypress & playwright']
startButton = //button[@name='start']
genderRadioButtons=//label[contains(text(),'ale')]
countryDropdown=//select[@id='country']
pointMeButton = //button[@class='dropbtn']


